# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# For a sample file, please refer to https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/userprefs.t2

exec = gsettings set org.gnome.desktop.interface gtk-theme 'Edge-Runner'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

# Custom battery alert
exec-once = ~/.local/bin/battery-alert

decoration {
    rounding = 10
    shadow {
        enabled = false
    }
}

general {
    gaps_in = 3
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(90ceaaff) rgba(ecd3a0ff) 45deg
    col.inactive_border = rgba(86aaeccc) rgba(93cee9cc) 45deg
}
