" --- Indentation settings ---
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4

" --- General options ---
set mouse=
set clipboard=unnamedplus

" --- Display settings ---
set number
set relativenumber
set wrap

" --- File handling ---
set noswapfile
set undofile
set nobackup

" --- Search settings ---
set ignorecase
set smartcase
set hlsearch

" --- Appearance ---
let mapleader = " "
let maplocalleader = "\\"

" --- Window navigation ---
nnoremap <C-k> <C-w>k
nnoremap <C-j> <C-w>j
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

" --- Clear search highlighting ---
nnoremap <leader>h :nohlsearch<CR>

" --- Better indentation ---
vnoremap < <gv
vnoremap > >gv

" --- Move lines ---
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
inoremap <A-j> <Esc>:m .+1<CR>==gi
inoremap <A-k> <Esc>:m .-2<CR>==gi
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv

" --- Open terminal to the right ---
nnoremap <leader>t :belowright vert term<CR>

" --- Disable arrow keys ---
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>
inoremap <Up> <Nop>
inoremap <Down> <Nop>
inoremap <Left> <Nop>
inoremap <Right> <Nop>

