font_family      CaskaydiaCove Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
enable_audio_bell no
font_size 12
window_padding_width 25
include theme.conf
cursor_trail 1
background_opacity 1

# this will override stuff if not empty
include userprefs.conf

